version: '3'
services:
  locator:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    image: ubuntu
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=locator
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
