export const FETCH_OUR_USER_IN_PROGRESS = 'FETCH_OUR_USER_IN_PROGRESS';
export const FETCH_OUR_USER_WITH_ERRORS = 'FETCH_OUR_USER_WITH_ERRORS';
export const FETCH_OUR_USER_SUCCESSFULLY = 'FETCH_OUR_USER_SUCCESSFULLY';
