version: '2.2'
services:
  radio:
    build: .
    depends_on:
      - redis
      - db
    restart: "always"
    stop_grace_period: 3s
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 10
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    ports:
      - "4553:4553"
  redis:
    image: redis:5-alpine
    restart: "always"
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 128
    volumes:
      - ./data/redis:/data
  db:
    image: postgres:11-alpine
    restart: "always"
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 128
    environment:
      POSTGRES_USER: radio
      POSTGRES_PASSWORD: radio
      POSTGRES_DB: radio
    volumes:
      - ./data/pg:/var/lib/postgresql/data
