FROM golang:1.13-buster

RUN curl -sL https://deb.nodesource.com/setup_13.x | bash -
RUN apt-get install -y nodejs

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update
RUN apt-get install -y yarn

ENV APP_DIR /go/src/github.com/HackerDom/ructfe-2019/services/radio/
RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR
