FROM ubuntu:18.04

RUN set -eux

RUN apt update && \
    apt install -y g++ make libboost1.65-all-dev

ADD src /tmp/src
ADD Makefile /tmp/Makefile

WORKDIR /tmp/

RUN make

ENTRYPOINT ["sleep", "infinity"]
