version: '2.2'
services:
  patrol:
    build: .
    ports:
      - "23179:23179"
    volumes:
      - ./storage:/app/storage
      - ./patrol.properties:/app/patrol.properties
    restart: always
    # memory limit
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 256
