version: "2"
services:
  app:
    environment:
      - EXPRESS_PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
