version: "2.2"
services:
  staff:
    environment:
      - EXPRESS_PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    build: .
    restart: "always"
    stop_grace_period: 3s

    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 100

    ulimits:
      nofile:
        soft: 12000
        hard: 12000

    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 100
