export const PLAYLIST_CREATE_IN_PROGRESS = 'PLAYLIST_ADD_IN_PROGRESS';
export const PLAYLIST_CREATE_SUCCESSFULLY = 'PLAYLIST_ADD_SUCCESSFULLY';
export const PLAYLIST_CREATE_WITH_ERROR = 'PLAYLIST_ADD_WITH_ERROR';

export const PLAYLISTS_FETCH_IN_PROGRESS = 'PLAYLISTS_FETCH_IN_PROGRESS';
export const PLAYLISTS_FETCH_SUCCESSFULLY = 'PLAYLISTS_FETCH_SUCCESSFULLY';
export const PLAYLISTS_FETCH_WITH_ERRORS = 'PLAYLISTS_FETCH_WITH_ERRORS';

export const PLAYLIST_DELETE_IN_PROGRESS = 'PLAYLIST_DELETE_IN_PROGRESS';
export const PLAYLIST_DELETE_SUCCESSFULLY = 'PLAYLIST_DELETE_SUCCESSFULLY';
export const PLAYLIST_DELETE_WITH_ERRORS = 'PLAYLIST_DELETE_WITH_ERRORS';

export const PLAYLIST_FETCH_IN_PROGRESS = 'PLAYLIST_FETCH_IN_PROGRESS';
export const PLAYLIST_FETCH_SUCCESSFULLY = 'PLAYLIST_FETCH_SUCCESSFULLY';
export const PLAYLIST_FETCH_WITH_ERRORS = 'PLAYLIST_FETCH_WITH_ERRORS';
