FROM mcr.microsoft.com/dotnet/core/sdk:3.0

RUN apt-get update -yq 
RUN apt-get install curl gnupg -yq 
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs
RUN apt-get install libssl-dev

COPY ./Household /app/Household
WORKDIR /app/Household/ClientApp
RUN npm install


CMD ["bash", "-c", "cd /app/Household && dotnet restore && dotnet publish -c Release -o publish"]
