---
- name: Uploading service
  debug:
    msg: "Uploading {{ service_name }}"

- name: Create service user
  user:
    name: "{{ service_name }}"
    groups: docker
    append: yes

- name: Copy service
  synchronize:
    src: "{{ playbook_dir }}/../services/{{ service_name }}/"
    dest: "/home/{{ service_name }}/"
    rsync_opts: ["--exclude=.rsync-filter", "--exclude=before_image_build.sh"]

- name: Check permissions
  file:
    name: "/home/{{ service_name }}/"
    recurse: yes
    owner: "{{ service_name }}"
    group: "{{ service_name }}"

- name: Copy unit
  template: src=unit.j2 dest=/lib/systemd/system/{{ service_name }}.service

- name: Enable service
  systemd: name={{ service_name }} daemon_reload=yes enabled=yes

- name: Pull dependencies
  command: docker-compose pull
  args:
    chdir: "/home/{{ service_name }}/"
    warn: no

- name: Build docker images
  command: docker-compose build
  args:
    chdir: "/home/{{ service_name }}/"
    warn: no

