export const REGISTER_USER_IN_PROGRESS = 'REGISTER_USER_IN_PROGRESS';
export const REGISTER_USER_SUCCESFULLY = 'REGISTER_USER_SUCCESFULLY';
export const REGISTER_USER_WITH_ERRORS = 'REGISTER_USER_WITH_ERRORS';
